### ISSUE TITLE
小哥，为什么找不到源代码？

### ISSUE THREAD

**Issue by solider245** [jhanjhenyi/nba-news-crawler#2]
我是个新手，完全看不到……

**Comment by jhanjhenyi** [comment]
如果你是在問我這個 repo 的原始碼的話
就在 Code 那頁啊...

**Comment by solider245** [comment]
> 如果你是在問我這個 repo 的原始碼的話
> 就在 Code 那頁啊...

怎么和别人的不一样。还是不太懂。能加个动图写清楚一点吗？说不定也能让这个项目得到更多人的关注？

**Comment by jhanjhenyi** [comment]
> 
> 
> > 如果你是在問我這個 repo 的原始碼的話
> > 就在 Code 那頁啊...
> 
> 怎么和别人的不一样。还是不太懂。能加个动图写清楚一点吗？说不定也能让这个项目得到更多人的关注？

如果你是在問 Django 的程式碼的話在 nba_news 資料夾裡喔
https://github.com/jhanjhenyi/nba-news-crawler/tree/master/nba_news

至於資料夾結構的不一樣，純粹就是每個人設計的結構不同

**Comment by solider245** [comment]
> > > 如果你是在問我這個 repo 的原始碼的話
> > > 就在 Code 那頁啊...
> > 
> > 
> > 怎么和别人的不一样。还是不太懂。能加个动图写清楚一点吗？说不定也能让这个项目得到更多人的关注？
> 
> 如果你是在問 Django 的程式碼的話在 nba_news 資料夾裡喔
> https://github.com/jhanjhenyi/nba-news-crawler/tree/master/nba_news
> 
> 至於資料夾結構的不一樣，純粹就是每個人設計的結構不同

搞定了，先谢谢了哈
